package com.hermes.agent.controller;

import com.hermes.agent.agent.SimpleAgent;
import com.hermes.agent.config.ErrorHandlingProperties;
import com.hermes.agent.memory.MemoryStore;
import com.hermes.agent.service.ConversationCurator;
import com.hermes.agent.service.SessionExporter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.util.List;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * ConversationController 的错误处理测试。
 */
class ConversationControllerErrorHandlingTest {

    private MockMvc mockMvc;
    private SimpleAgent agent;

    @BeforeEach
    void setUp() {
        agent = mock(SimpleAgent.class);
        MemoryStore memoryStore = mock(MemoryStore.class);
        ConversationCurator curator = mock(ConversationCurator.class);
        SessionExporter exporter = mock(SessionExporter.class);
        ErrorHandlingProperties props = new ErrorHandlingProperties();
        when(agent.getToolCallTracker()).thenReturn(new ToolCallTracker(props));
        when(memoryStore.getAllEntries()).thenReturn(java.util.Map.of());
        mockMvc = MockMvcBuilders.standaloneSetup(new ConversationController(agent, memoryStore, curator, exporter)).build();
    }

    @Test
    void streamRequestCreatesSseEmitter() throws Exception {
        mockMvc.perform(post("/api/conversations/stream")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"message\":\"hello\"}"))
                .andExpect(status().isOk());

        verify(agent).streamConversation(anyString(), eq("hello"), any());
    }

    @Test
    void sessionIdAutoGeneratedWhenNotProvided() throws Exception {
        mockMvc.perform(post("/api/conversations/stream")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"message\":\"test\"}"))
                .andExpect(status().isOk());

        verify(agent).streamConversation(
                argThat(s -> s != null && !s.isBlank()),
                eq("test"),
                any());
    }

    @Test
    void healthEndpointReturnsOk() throws Exception {
        when(agent.getAvailableTools()).thenReturn(List.of("datetime", "echo"));

        mockMvc.perform(get("/api/conversations/health"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status").value("UP"))
                .andExpect(jsonPath("$.tools").value("datetime, echo"));
    }

    @Test
    void postConversationReturnsErrorResponse() throws Exception {
        when(agent.runConversation(anyString(), eq("hello")))
                .thenReturn("抱歉，处理您的请求时出现错误 (network_error): 网络连接异常，正在重试...");

        mockMvc.perform(post("/api/conversations")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"message\":\"hello\",\"sessionId\":\"s1\"}"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.success").value(true))
                .andExpect(jsonPath("$.message").value("抱歉，处理您的请求时出现错误 (network_error): 网络连接异常，正在重试..."));
    }
}
